### ISSUE TITLE
Belgede belirtilen dernek isminin değiştirilmesi 

### ISSUE THREAD

**Issue by furkanonder** [lkdtr/coc#1]
Belgede belirtilen dernek ismi olan ```Özgür Yazılım Derneği``` yerine ```Linux Kullanıcıları Derneği```'nin kullanılması gerektiğini düşünüyorum.

**Comment by yasarcelep** [comment]
Hemfikirim, yönetim kurulu mu ilgili yoksa disiplin'le alakalı bir kısım olmalı mı emin değilim.

**Comment by bmericc** [comment]
Hali hazırda disiplin kurulu sadece danışma kurulu gibi çalışıyor. Bu sebeple disiplin kurulu yazılsa da yaptırım yetkisi mevcut disiplin yönetmeliğine ve tüzüğe göre yönetim kurulunda. Bu sebeple şimdilik yönetim kurulu yazalım. Sonrasında Daha aktif bir disiplin kurulumuz olduğunda değiştiriz.

**Comment by ooguz** [comment]
#2 kapatır
