### ISSUE TITLE
Raconu yerine İletişim Etiği

### ISSUE THREAD

**Issue by bmericc** [lkdtr/coc#3]
Merhaba

Yılar önce eposta listeleri için hazırlanmış bir dökümanda etik tabiri kullanılmış. https://liste.linux.org.tr/etik.php 

Bana racon yerine iletişim etiği demek daha doğru geldi.

Ek olarak listenin metinleri aldığı site kapalı ama web arşivde şurada https://web.archive.org/web/20210118194619/http://kutluata.net/BilisimEtik.aspx

**Comment by ooguz** [comment]
Sadece "iletişim etiği" dersek kapsamı daraltmış oluruz, çünkü yalnızca e-posta listesi değil, insanların yüzyüze geldiği etkinliklerdeki hal ve hareketleri de kapsıyor metin. Ayrıca metnin yaptırım gücü de var, sadece tavsiye vermiyor. O yüzden isim değişecekse "davranış kuralları" demek daha doğru olacaktır kanımca.

**Comment by ooguz** [comment]
CoC'nin bir kural listesi değil, _a priori_ bilinmesi ve uygulanması gereken davranışların yazıya dökülmüş hali olmasından dolayı, tartışma sonuçlanana kadar rehberlere "davranış yönergesi" yazdık. 

"Racon" ifadesi bunun tam olarak Türkçe'deki karşılığı olsa da, maalesef ki kötü şöhretli bir kelime. O yüzden kullanılmamak istenmesi de anlaşılır, nihai olarak "davranış yönergesi" şeklinde bir öneri yapayım.

**Comment by bmericc** [comment]
Davranış yönergesi her halukarda racondan daha iyi. Daha iyi bir öneri yoksa "davranış yönergesi" olsun

**Comment by kunthar** [comment]
Racon, Turkce'deki sosyolojik anlam itibariyla baska bir anlami isaret ediyor. 
“(argo) kabadayı nizamı” [Ahmed Rasim, Şehir Mektupları, 1897]
Kelime anlamsal olarak dogru ama kullanimsal olarak ulkedeki anlami baska tinliyor. 
[[2]](https://birikimdergisi.com/guncel/10614/omerta-beka-racon#_ftnref2) Hulki Aktunç, Türkçe’nin Büyük Argo Sözlüğü (Tanıklarıyla), YKY, 1998.

Nitekim Aktunç[[2]](https://birikimdergisi.com/guncel/10614/omerta-beka-racon#_ftn2), racon kelimesinin argoda da usul, âdet, yol erkân anlamlarına geldiğini belirtir. “Kabadayı” âleminde “racon kesmek”,  kural koymak, erkânı kurmak, “rükn”ü, yani “temeli”, “esası” belirlemektir.
